# 基本設定
## 256色を使用する
set -g default-terminal "screen-256color"
set -g terminal-overrides 'xterm*:color=256'
## ESC キーの遅延を解消する
set -s escape-time 0
## Status lisne を更新する間隔を1秒にする
set-option -g status-interval 1
## ウィンドウのインデックスを1から始める
set -g base-index 1
## 自動リネームを無効にする
set-option -g allow-rename off
## ウィンドウステータスを空にする
set-option -g window-status-format ""
set-option -g window-status-current-format ""

# status line の設定
## 両端にスペースを挿入する
set -g status-left " "
set -g status-right " "
## status line の背景色
set -g status-bg "#002b36"
## status line の文字を太文字にする
set -g status-style "bold"
## pane の border を非表示にする
set-option -g pane-border-format ""
## status-left
set-option -g status-left-length 300
set-option -g status-left  "\
#[bg=#b58900]#[fg=#002d36]  #(~/dotfiles/tmux/ip.sh)  \
#[fg=#b58900]#[bg=#002d36]\
#[fg=#002d36]#[bg=#d33682] \
#[fg=#ece8d6]#[bg=#d33682] #(~/dotfiles/tmux/cpu.sh)  \
#[fg=#d33682]#[bg=#002d36]\
#[fg=#0d2a34]#[bg=#2aa198] \
#[bg=#2aa198]#[fg=#ece8d6] #W  \
#[fg=#2aa198]#[bg=#002d36]"
## status-right
set-option -g status-right-length 300
set-option -g status-right  "\
#[fg=#268bd2]#[bg=#002d36]\
#[bg=#268bd2]#[fg=#ece8d6]  #(~/dotfiles/tmux/weather.sh) \
#[fg=#002d36]#[bg=#268bd2] \
#[fg=#859900]#[bg=#002d36]\
#[bg=#859900]#[fg=#073642] #h "


# 操作系
## mouse の操作を無効にする
set-option -g mouse off
bind h set-option -g mouse \; display-message 'Mouse mode toggled!'
