# 基本設定
## 256色を使用する
set -g default-terminal "screen-256color"
set -g terminal-overrides 'xterm*:color=256'
## ESC キーの遅延を解消する
set -s escape-time 0
## Status lisne を更新する間隔を1秒にする
set-option -g status-interval 1
## ウィンドウのインデックスを1から始める
set -g base-index 1
## 自動リネームを無効にする
set-option -g allow-rename off
## ウィンドウステータスを空にする
set-option -g window-status-format ""
set-option -g window-status-current-format ""

# status line の設定
## 両端にスペースを挿入する
set -g status-left " "
set -g status-right " "
## status line の背景色
set -g status-bg "#101115"
## status line の文字を太文字にする
set -g status-style "bold"
## pane の border を非表示にする
set-option -g pane-border-format ""
## status-left
set-option -g status-left-length 300
set-option -g status-left  "\
#[bg=#cad0d8]#[fg=#101115]  #(~/dotfiles/tmux/ip.sh)  \
#[fg=#8e9195]#[bg=#101115]\
#[fg=#101115]#[bg=#cb689f] \
#[fg=#ece8d6]#[bg=#cb689f] #W  \
#[fg=#884d6e]#[bg=#101115]\
#[fg=#0d2a34]#[bg=#3f7286] \
#[bg=#3f7286]#[fg=#ece8d6] #(~/dotfiles/tmux/current_dir.sh)  \
#[fg=#1d4e61]#[bg=#101115]"
## status-right
set-option -g status-right-length 300
set-option -g status-right  "\
#[fg=#cad0d8]#[bg=#101115]\
#[bg=#cad0d8]#[fg=#101115]  #(~/dotfiles/tmux/weather.sh) \
#[fg=#101115]#[bg=#cad0d8] \
#[fg=#4a6598]#[bg=#101115]\
#[bg=#78a2f1]#[fg=#ece8d6] #h "


# 操作系
## mouse の操作を無効にする
set-option -g mouse off
