# 基本設定
## 256色を使用する
set -g default-terminal "screen-256color"
set -g terminal-overrides 'xterm*:color=256'
## ESC キーの遅延を解消する
set -s escape-time 0
## Status lisne を更新する間隔を1秒にする
set-option -g status-interval 1
## ウィンドウのインデックスを1から始める
set -g base-index 1
## 自動リネームを無効にする
set-option -g allow-rename off
## ウィンドウステータスを空にする
set-option -g window-status-format ""
set-option -g window-status-current-format ""

# status line の設定
## 両端にスペースを挿入する
set -g status-left " "
set -g status-right " "
## status line の背景色
set -g status-bg "#0d2a34"
## status line の文字を太文字にする
set -g status-style "bold"
## pane の border を非表示にする
set-option -g pane-border-format ""
## status-left
set-option -g status-left-length 200
set-option -g status-left  "\
#[bg=#ece8d6]#[fg=#0d2a34]  #(~/dotfiles/tmux/ip.sh)  \
#[fg=#abaaa9]#[bg=#0d2a34]\
#[fg=#0d2a34]#[bg=#4689cc] \
#[fg=#ece8d6]#[bg=#4689cc] #W  \
#[fg=#4774a1]#[bg=#0d2a34]\
#[fg=#0d2a34]#[bg=#ae8a2c] \
#[bg=#ae8a2c] #(~/dotfiles/tmux/current_dir.sh)  \
#[fg=#877033]#[bg=#0d2a34]"
## status-right
set-option -g status-right  "\
#[fg=#abaaa9]#[bg=#0d2a34]\
#[bg=#ece8d6]#[fg=#0d2a34]  #(~/dotfiles/tmux/weather.sh) \
#[fg=#0d2a34]#[bg=#ece8d6] \
#[fg=#6d7928]#[bg=#0d2a34]\
#[bg=#88982d]#[fg=#0d2a34] #h "


# 操作系
## mouse の操作を有効にする
set-option -g mouse on
bind -n WheelUpPane if-shell -F -t = "#{mouse_any_flag}" "send-keys -M" "if -Ft= '#{pane_in_mode}' 'send-keys -M' 'copy-mode -e'"
bind -n WheelDownPane select-pane -t= \; send-keys -M
## クリップボートとの連携
bind-key -T copy-mode-vi y send-keys -X copy-pipe-and-cancel "pbcopy"
bind-key -T copy-mode-vi MouseDragEnd1Pane send-keys -X copy-pipe-and-cancel "pbcopy"
bind-key -T copy-mode-vi Enter send-keys -X copy-pipe-and-cancel "pbcopy"

